// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"terrorblade/cmd/terrorbladed/internal/handlers"
	"terrorblade/cmd/terrorbladed/internal/services"
	"terrorblade/kit/server"
	"terrorblade/repositories"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitializeMain() *App {
	db := NewMySQLConnection()
	userRepository := repositories.NewUserRepository()
	userService := services.NewUserService(db, userRepository)
	userHandler := handlers.NewUserHandler(userService)
	routingFn := NewRoutingFn(userHandler)
	serverServer := server.NewServer(routingFn)
	app := NewApp(db, serverServer)
	return app
}
