// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	handlers2 "terrorblade/cmd/terrorbladed/internal/handlers"
	"terrorblade/cmd/terrorbladed/internal/services"
	"terrorblade/handlers"
	"terrorblade/kit/server"
	"terrorblade/repositories"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitializeMain() *App {
	healthCheckHandler := handlers.NewHealthCheckHandler()
	db := NewMySQLConn()
	userRepository := repositories.NewUserRepository()
	userService := services.NewUserService(db, userRepository)
	userHandler := handlers2.NewUserHandler(userService)
	handlersHandlers := handlers2.NewHandlers(healthCheckHandler, userHandler)
	routingFn := NewRoutingFn(handlersHandlers)
	serverServer := server.NewServer(routingFn)
	app := NewApp(serverServer)
	return app
}
